services:
  - type: web
    name: gazpromtraining
    plan: free
    region: frankfurt
    dockerfile: Dockerfile
    envVars:
      - key: DB_HOST
        value: "localhost"  # Для локальной БД: localhost
      - key: DB_USER
        value: "root"        # Для XAMPP: root
      - key: DB_PASSWORD
        value: ""    # Для XAMPP: пустая строка
      - key: DB_NAME
        value: "gazprom_db"
    healthCheckPath: /index.php