services:
  - type: web
    name: gazpromtraining
    env: php
    plan: free
    region: frankfurt
    buildCommand: ""  // Оставьте ПУСТЫМ для PHP!
    startCommand: php -S 0.0.0.0:$PORT -t .
    envVars:
      - key: PORT
        value: 10000
